/**
 * Agent 5 — DeFi Risk Report Generator
 * Orchestrates Agents 1-4 via shared lib (in-process, no HTTP calls)
 *
 * POST /api/v1/agents-internal/wasi-risk-report
 * Body: {
 *   token_address: string          (required)
 *   feed_address?:  string         (Chainlink feed; defaults to AVAX/USD)
 *   token_name?:    string         (fallback: read from on-chain)
 *   token_symbol?:  string         (fallback: read from on-chain)
 *   description?:   string
 * }
 */
import { NextRequest, NextResponse } from 'next/server'
import { verifyInternalSecret } from '@/lib/admin/verifyInternalSecret'
import { readChainlinkFeed }  from '@/lib/defi-risk/chainlink'
import { analyzeOnChain }     from '@/lib/defi-risk/onchain'
import { auditContract }      from '@/lib/defi-risk/auditor'
import { analyzeSentiment }   from '@/lib/defi-risk/sentiment'
import { computeRiskScore, generateSummary } from '@/lib/defi-risk/riskScorer'
import type { RiskReport }    from '@/lib/defi-risk/types'

const DEFAULT_FEED = (process.env.CHAINLINK_AVAX_USD_FEED ?? '').trim()

export async function POST(request: NextRequest) {
  const authError = verifyInternalSecret(request)
  if (authError) return authError

  let body: Record<string, unknown> = {}
  try { body = await request.json() } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  // Parse input (gateway wraps in { input: "..." } or direct object)
  let params: Record<string, string | undefined>
  if (typeof body.input === 'string') {
    try { params = JSON.parse(body.input) } catch { params = { token_address: body.input } }
  } else {
    params = body as Record<string, string | undefined>
  }

  const tokenAddress = String(params.token_address ?? '').trim()
  if (!tokenAddress || !/^0x[0-9a-fA-F]{40}$/.test(tokenAddress)) {
    return NextResponse.json({ error: 'Valid token_address required' }, { status: 400 })
  }

  const feedAddress  = String(params.feed_address  ?? DEFAULT_FEED ?? '').trim()
  const inputName    = String(params.token_name    ?? '').trim()
  const inputSymbol  = String(params.token_symbol  ?? '').trim()
  const description  = String(params.description   ?? '').trim() || undefined

  const startMs = Date.now()

  // ── Run Agents 1 + 2 in parallel (both are on-chain reads, independent) ──
  const [chainlinkResult, onchainResult] = await Promise.all([
    feedAddress
      ? readChainlinkFeed(feedAddress, inputSymbol || 'TOKEN')
      : Promise.resolve(null),
    analyzeOnChain(tokenAddress),
  ])

  // Resolve name/symbol from on-chain if not provided
  const tokenName   = inputName   || onchainResult.name   || tokenAddress.slice(0, 10) + '...'
  const tokenSymbol = inputSymbol || onchainResult.symbol || '???'

  // ── Run Agents 3 + 4 in parallel (both use Groq, independent) ────────────
  const [auditResult, sentimentResult] = await Promise.all([
    auditContract(tokenAddress),
    analyzeSentiment(tokenName, tokenSymbol, description),
  ])

  // ── Agent 5: Score + Report ───────────────────────────────────────────────
  const riskScore = computeRiskScore(chainlinkResult, onchainResult, auditResult, sentimentResult)
  const summary   = generateSummary(tokenAddress, riskScore, chainlinkResult, onchainResult, auditResult, sentimentResult)

  const report: RiskReport = {
    token_address: tokenAddress,
    generated_at:  new Date().toISOString(),
    risk_score:    riskScore,
    agents: {
      chainlink:  chainlinkResult,
      onchain:    onchainResult,
      audit:      auditResult,
      sentiment:  sentimentResult,
    },
    summary,
    disclaimer: 'This report is generated by AI agents and on-chain data. It is not financial advice. Always DYOR.',
  }

  return NextResponse.json({
    result: report,
    meta: {
      agent:      'wasi-risk-report',
      latency_ms: Date.now() - startMs,
      powered_by: 'chainlink+avalanche-rpc+groq',
    },
  })
}

export async function GET() {
  return NextResponse.json({
    schema: 'wasiai/agent-spec/v1',
    slug:   'wasi-risk-report',
    name:   'DeFi Risk Report Generator',
    input: {
      example: {
        token_address: '0x5425890298aed601595a70AB815c96711a31BC65',
        feed_address:  '0x5498BB86BC934c8D34FDA08E81D444153d0D06aD',
        token_name:    'USD Coin',
        token_symbol:  'USDC',
      },
    },
  })
}
